# serivce name
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: transaccion-service
  datasource:
    url: jdbc:mysql://mysql-server:3306/db_sm_valoracion?
    username: admin
    password: admin
#Tomcat Embedded Server Configuration
server:
  port: 9081

logging:
  lever:
    root: INFO
    org.springframework.web: INFO
    com.howtodoinjava: INFO
    org.hibernate: INFO
  file:
    name: /opt/log/transaccion.log
    max-history: 5
  pattern:
    rolling-file-name: transaccion-%d{yyyy-MM-dd}.%i.log
    console: "%d{yyyy-MM--dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

