# serivce name
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: pedido-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_sm_pedido?
    username: root
    password: toor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Tomcat Embedded Server Configuration
server:
  port: 9009

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}