# serivce name
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: pedido-service
  datasource:
    url: jdbc:mysql://mysql-server:3306/db_sm_pedido?
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Tomcat Embedded Server Configuration
server:
  port: 9009

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}