# serivce name
spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_sm_pedido?verifyServerCertificate=false&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
#Tomcat Embedded Server Configuration
server:
  port: 9009

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}