version: '3.9'
services:
  mysql-server:
    image: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: toor
    container_name: mysql-container
    ports:
      - 33061:3306
    networks:
      - 'dockernetflix-network'
  order-microservice:
    image: order-service:order-sm
    restart: always
    container_name: order-container
    depends_on:
      - mysql-server
    networks:
      - 'dockernetflix-network'
networks:
  dockernetflix-network: #necesitamos crear en una red para alojar los servicios en ella y que puedan comunicarse entre sí
 