# serivce name
spring:
  application:
    name: inventario-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_sm_producto?
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Tomcat Embedded Server Configuration
server:
  port: 9560
#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}