# serivce name
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
  #    enabled: false
#Tomcat Embedded Server Configuration
server:
  port: 8089
logging:
  lever:
    root: INFO
    org.springframework.web: INFO
    com.howtodoinjava: INFO
    org.hibernate: INFO
  file:
    name: /opt/log/gateway.log
    max-history: 5
  pattern:
    rolling-file-name: gateway-%d{yyyy-MM-dd}.%i.log
    console: "%d{yyyy-MM--dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}